name: Single test

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome
          - firefox
          
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: checkout
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Selenium setup
    - uses: adrielcodeco/docker-compose-run-action@v1
      with:
        compose-file: docker-compose.yml
        run-flags: -d

    - name: Test with pytest
      run: |
        pytest --alluredir=allure-results --browser=${{ github.event.inputs.browser }}
    - name: Allure results
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        allure_report: allure-report
        gh_pages: gh-pages
        allure_history: allure-history
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
